In [2]:
# Analysis of proximity measure for various attribute type
# A. Nominal
# B. Binary (Sym / Asym)
# C. Numerical (Manhattan / Euclidean)
# D. Ordinal

In [3]:
# Proximity measures are mainly mathematical techniques that calculate the similarity/dissimilarity of data points.

## Nominal Attributes - dissimilarity Measure

    - d(i,j) = (p -m)/p
    - p is the number of attributes in dataframe (other than the identifiier column )
    - m is the number of similar points for given pair

In [4]:
import pandas as pd

data = {
    "Roll No": [1,2,3,4,5],
    "Grade": ['A','B','C','A','E']
}


# convert the data into pandas dataframe
df = pd.DataFrame(data).set_index("Roll No")

In [5]:
df.head()

        Grade
Roll No
1           A
2           B
3           C
4           A
5           E

In [6]:
def dissimilarity_mtx_for_nominal(df, p):

    n = len(df)

    mtx = [[0.0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(i+1, n):

            m = 0  # count of similar points
            if(df.iloc[i]['Grade'] == df.iloc[j]['Grade']):
                m += 1
            dis = (p-m) / p
            print(f'Calulating {i} and {j} dissimilarity score: {dis}')

            # mtx[i][j] = dis # for upper triangular mtx
            mtx[j][i] = dis
    return mtx

In [7]:
mtx = dissimilarity_mtx_for_nominal(df, 1)
mtx

Calulating 0 and 1 dissimilarity score: 1.0
Calulating 0 and 2 dissimilarity score: 1.0
Calulating 0 and 3 dissimilarity score: 0.0
Calulating 0 and 4 dissimilarity score: 1.0
Calulating 1 and 2 dissimilarity score: 1.0
Calulating 1 and 3 dissimilarity score: 1.0
Calulating 1 and 4 dissimilarity score: 1.0
Calulating 2 and 3 dissimilarity score: 1.0
Calulating 2 and 4 dissimilarity score: 1.0
Calulating 3 and 4 dissimilarity score: 1.0

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 0.0],
 [1.0, 1.0, 1.0, 1.0, 0.0]]

In [29]:
data = {
    "id": [1,2,3,4],
    "attribute-1": [20, 40, 20, 30],
    "attribute-2": ['AA', 'BB', 'AA' ,'CC',]
}

df1 = pd.DataFrame(data).set_index("id")
df1.head()

    attribute-1 attribute-2
id
1            20          AA
2            40          BB
3            20          AA
4            30          CC

### Below code is more gneric formula this will work for all type of dataframes

In [30]:
def nominal_dissimilarity_measure(df):
    n = len(df)
    p = df.shape[1]   # number of attributes

    mtx = [[0.0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(i + 1, n):

            m = 0

            # Compare every attribute
            for column in df.columns:
                if df.iloc[i][column] == df.iloc[j][column]:
                    m += 1

            dis = (p - m) / p

            # Matrix is symmetric
            # mtx[i][j] = dis
            mtx[j][i] = dis

    return mtx

In [31]:
mtx = nominal_dissimilarity_measure(df1)
mtx

[[0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [1.0, 1.0, 1.0, 0.0]]